name: '.NET Github Action Template' # TODO: Set the name
description: 'An example NET Github action.' # TODO: Set the description
author: 'Calvin Wilkinson (KinsonDigital)'
branding:
  icon: settings
  color: purple
inputs: # TODO: Add as many inputs as needed
  message:
    description: 'Prints a message to the console.'
    required: true

outputs: # TODO: Re-enable if you want to have action outputs
  sample-output: # This is the name of the output
    description: 'Sample output.'

# These are the arguments that are passed into the console app
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--message'
  - ${{ inputs.message }}
