name: ✔Build Status Check


env:
  NET_SDK_VERSION: 6.0.300 # TODO: Verify that this matches the version the project is using


on:
  workflow_dispatch:
    paths-ignore:
      - ".github/**"
      - "Documentation/**"
      - '.editorconfig'
      - '*.runsettings'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - '*.yml'
      - '.vscode/**'
      - '*.sln'


jobs:
  determine_build_config:
    name: Determine Build Configuration
    runs-on: ubuntu-latest
    outputs:
      build-config: ${{ steps.get-build-config.outputs.build-config }}
    steps:
      - name: Get Build Config
        id: get-build-config
        shell: pwsh
        run: |
          # If the destination branch that the pull request is merging into is the master, do a release build
          if ( "${{ github.base_ref }}" -eq "master") {
            Write-Host "::set-output name=build-config::Release";
          } else { # Any other branch than master, do a debug build
            Write-Host "::set-output name=build-config::Debug";
          }

  get_sdk_version:
    name: Get SDK Version
    runs-on: ubuntu-latest
    outputs:
      sdk-version: ${{ steps.get-sdk-version.outputs.sdk-version }}
    steps:
      - name: Get SDK Version From Environment Variable
        id: get-sdk-version
        shell: pwsh
        run: Write-Host "::set-output name=sdk-version::${{ env.NET_SDK_VERSION }}";

  # Build Main Projects
  build_branch_validator: # TODO: Update this job name
    name: Build BranchValidator Project # TODO: Update this project name
    needs: [determine_build_config, get_sdk_version]
    uses: KinsonDigital/Infrastructure/.github/workflows/build-status-check.yml@master
    with:
      project-name: "BranchValidator" # TODO: Update this project name
      build-config: ${{ needs.determine_build_config.outputs.build-config }}
      net-sdk-version: ${{ needs.get_sdk_version.outputs.sdk-version }}

  build_branch_validator_shared: # TODO: Update this job name
    name: Build BranchValidatorShared Project # TODO: Update this project name
    needs: [determine_build_config, get_sdk_version]
    uses: KinsonDigital/Infrastructure/.github/workflows/build-status-check.yml@master
    with:
      project-name: "BranchValidatorShared" # TODO: Update this project name
      build-config: ${{ needs.determine_build_config.outputs.build-config }}
      net-sdk-version: ${{ needs.get_sdk_version.outputs.sdk-version }}

  #----------------------------------------------------------------------

  # Build all of the unit testing projects
  build_testing_shared: # TODO: Update this job name
    name: Build TestingShared
    needs: [determine_build_config,
            get_sdk_version,
            build_branch_validator,
            build_branch_validator_shared,
            build_script_generator]
    uses: KinsonDigital/Infrastructure/.github/workflows/build-status-check.yml@master
    with:
      project-name: "TestingShared"
      build-config: ${{ needs.determine_build_config.outputs.build-config }}
      net-sdk-version: ${{ needs.get_sdk_version.outputs.sdk-version }}

  build_branch_validator_tests: # TODO: Update this job name
    name: Build BranchValidatorTests Project # TODO: Update this project name
    needs: [determine_build_config,
            get_sdk_version,
            build_branch_validator,
            build_testing_shared]
    uses: KinsonDigital/Infrastructure/.github/workflows/build-status-check.yml@master
    with:
      project-name: "BranchValidatorTests" # TODO: Update this project name
      build-config: ${{ needs.determine_build_config.outputs.build-config }}
      net-sdk-version: ${{ needs.get_sdk_version.outputs.sdk-version }}
